package com.demo.model;

public class Event {
	
		private String Id; //Event Id :  Auto Generated by Database.

		private String eventName; //Name of Event
		
		private String venue; //Venue of Event.
		
		private String eventDate; //Date of Event.
		
		private String about; //About the Event.
		
		private int tickets = 0; //Number of tickets for the event.
		
		//Getters and Setters
		public String getEventName() {
			return eventName;
		}

		public void setEventName(String eventName) {
			this.eventName = eventName;
		}

		public String getVenue() {
			return venue;
		}

		public void setVenue(String venue) {
			this.venue = venue;
		}

		public String getEventDate() {
			return eventDate;
		}

		public void setEventDate(String eventDate) {
			this.eventDate = eventDate;
		}

		public String getAbout() {
			return about;
		}

		public void setAbout(String about) {
			this.about = about;
		}

		public int getTickets() {
			return tickets;
		}

		public void setTickets(int tickets) {
			this.tickets = tickets;
		}

		public String getId() {
			return Id;
		}

		public void setId(String id) {
			Id = id;
		}

		@Override
		public String toString() {
			return "Event [Id=" + Id + ", eventName=" + eventName + ", venue=" + venue + ", eventDate=" + eventDate
					+ ", about=" + about + ", tickets=" + tickets + "]";
		}
		
		
}
